name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: db_titanic
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: admin
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v5

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - uses: php-actions/phpunit@v3

    - name: set-up php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0.11'
        extensions: imagick, pdo, pdo_mysql
 
    - name: version php
      run: php --version
    
    - name: Create token github
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        echo GITHUB_ACCESS_TOKEN

    - name: run script file to create db
      run: |
        chmod +x ./instal.sh
      shell: bash